spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pre_project?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: true
    profiles:
      include: database
  logging:
    level:
      org:
        springframework:
          orm:
            jpa: DEBUG
  server:
    servlet:
      encoding:
        force-response: true

mail:
  address:
    admin: admin@gmail.com